---
- name: test connection
  hosts: my-containers

  tasks:
  - name: Hi
    debug:
      msg: I can connect!

  - name: Touch a file, 
    file:
      path: /tmp/test.txt
      state: touch
      mode: u=rw,g=r,o=r(base)
